#include "showcase/codec.hpp"

namespace showcase {

namespace {
// The 256 entries of the reflected CRC-32 table, generated by tools/gen.cpp.
constexpr std::uint32_t table[256] = {
#include "showcase/crc32_table.inc"
};
} // namespace

std::uint32_t crc32(std::string_view data) {
	std::uint32_t crc = 0xffffffffu;
	for (char c : data) {
		crc = table[(crc ^ static_cast<unsigned char>(c)) & 0xffu] ^ (crc >> 8);
	}
	return crc ^ 0xffffffffu;
}

} // namespace showcase
