#include "showcase/codec.hpp"

// registry.inc is generated by tools/gen.cpp from the codecs in clue.cue:
// one X(key) line per codec.
#define X(key) extern const showcase::Codec codec_##key;
#include "showcase/registry.inc"
#undef X

namespace showcase {

namespace {
const Codec* const all[] = {
#define X(key) &codec_##key,
#include "showcase/registry.inc"
#undef X
};
} // namespace

std::span<const Codec* const> codecs() {
	return all;
}

const Codec* find(std::string_view key) {
	for (const Codec* c : all) {
		if (c->key == key) {
			return c;
		}
	}
	return nullptr;
}

} // namespace showcase
