// Package generate writes Ninja and compilation-database integration files.
package generate

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"slices"

	"github.com/Duncaen/go-ninja"

	"github.com/loov/clue/internal/config"
	"github.com/loov/clue/internal/toolchain"
)

// NinjaOptions holds options for generating build.ninja
type NinjaOptions struct {
	Config     *config.Config
	Variants   []string           // Variants to include (e.g., ["debug", "release"])
	BuildDir   string             // e.g., ".build"
	OutputPath string             // Output file path (default: build.ninja)
	Toolchain  string             // "clang" or "gcc"
	Platform   toolchain.Platform // Target platform
}

// Ninja creates a build.ninja file for the project
func Ninja(ctx context.Context, opts NinjaOptions) error {
	if opts.OutputPath == "" {
		opts.OutputPath = "build.ninja"
	}
	var buf bytes.Buffer
	if err := WriteNinjaTo(ctx, &buf, opts); err != nil {
		return err
	}
	return writeIfChanged(opts.OutputPath, buf.Bytes())
}

// generateVariantBuilds generates build statements for a single variant
func generateVariantBuilds(ctx context.Context, file *ninja.File, opts NinjaOptions, variant string, variantConfig config.Variant, targetOrder []string, tc toolchain.Toolchain, emitSharedRules bool) ([]string, error) {
	external, err := resolveExternalDependencies(ctx, opts.Config, tc, opts.BuildDir, variant, opts.Platform)
	if err != nil {
		return nil, err
	}
	outputs, err := generateDependencyBuilds(ctx, file, opts, variant, variantConfig, tc, emitSharedRules, external)
	if err != nil {
		return nil, err
	}

	targetModules := make(map[string]map[string]string)
	for _, targetName := range targetOrder {
		target, exists := opts.Config.Targets[targetName]
		if !exists {
			continue
		}

		// Generate build statements for this target
		targetOutputs, err := generateTargetBuilds(file, opts, variant, variantConfig, target, tc, emitSharedRules, targetModules, external)
		if err != nil {
			return nil, err
		}
		outputs = append(outputs, targetOutputs...)
	}

	return outputs, nil
}

// Helper functions

// Note: isCPlusPlusFile is defined in compdb.go and shared between both generators

// writeIfChanged writes content to file only if it differs from existing content
func writeIfChanged(path string, content []byte) error {
	existing, err := os.ReadFile(path)
	if err == nil && bytes.Equal(existing, content) {
		return nil // No change needed
	}

	return os.WriteFile(path, content, 0o644)
}

// WriteNinjaTo writes Ninja file content to a writer (for testing)
func WriteNinjaTo(ctx context.Context, w io.Writer, opts NinjaOptions) error {
	// Set defaults
	if opts.BuildDir == "" {
		opts.BuildDir = ".build"
	}
	if opts.Toolchain == "" {
		opts.Toolchain = opts.Config.Toolchain.Compiler
	}
	if opts.Platform.OS == "" {
		opts.Platform = toolchain.HostPlatform()
	}
	if len(opts.Variants) == 0 {
		for name := range opts.Config.Variants {
			opts.Variants = append(opts.Variants, name)
		}
		if len(opts.Variants) == 0 {
			opts.Variants = []string{"debug"}
		}
		slices.Sort(opts.Variants)
	}

	// Discover toolchain
	toolchain, err := configuredToolchain(opts.Config.Toolchain, opts.Toolchain, opts.Platform)
	if err != nil {
		return err
	}

	file := ninja.File{}

	// Header comment
	file = append(file, ninja.Comment{Lines: []string{"Generated by clue. Regenerate with: clue generate ninja"}})

	// Variables
	file = append(file, ninja.Comment{Lines: []string{"Build configuration"}})
	file = append(file, ninja.Var{Key: "builddir", Val: ".ninja_build"})
	file = append(file, ninja.Var{Key: "cc", Val: ninjaToolCommand(toolchain, toolchain.CC())})
	file = append(file, ninja.Var{Key: "cxx", Val: ninjaToolCommand(toolchain, toolchain.CXX())})
	file = append(file, ninja.Var{Key: "ar", Val: ninjaToolCommand(toolchain, toolchain.AR())})
	file = append(file, ninja.Var{Key: "clue", Val: "clue"})
	if toolchain.Name() == "msvc" {
		linker := "link.exe"
		if dir := filepath.Dir(toolchain.CC()); dir != "." {
			linker = filepath.Join(dir, linker)
		}
		file = append(file, ninja.Var{Key: "link", Val: NinjaPath(linker)})
	}

	// Rules
	file = append(file, ninja.Comment{Lines: []string{"Compilation rules"}})
	addNinjaRules(&file, toolchain.Name() == "msvc")
	file = append(file, ninja.Build{Rule: "phony", Out: []string{"force_external"}})

	targetOrder, err := config.ComputeBuildOrder(opts.Config)
	if err != nil {
		return err
	}
	variantOutputs := make(map[string][]string)

	for variantIndex, variant := range opts.Variants {
		variantConfig, exists := opts.Config.Variants[variant]
		if !exists && len(opts.Config.Variants) > 0 {
			return fmt.Errorf("variant %q not found", variant)
		}
		file = append(file, ninja.Comment{Lines: []string{"Variant: " + variant}})
		outputs, err := generateVariantBuilds(ctx, &file, opts, variant, variantConfig, targetOrder, toolchain, variantIndex == 0)
		if err != nil {
			return err
		}
		variantOutputs[variant] = outputs
	}

	// Phony targets
	file = append(file, ninja.Comment{Lines: []string{"Phony targets"}})
	for _, variant := range opts.Variants {
		if outputs, ok := variantOutputs[variant]; ok && len(outputs) > 0 {
			file = append(file, ninja.Build{
				Rule: "phony",
				In:   outputs,
				Out:  []string{variant},
			})
		}
	}

	if len(opts.Variants) > 0 {
		file = append(file, defaultTarget{targets: []string{opts.Variants[0]}})
	}

	_, err = file.WriteTo(w)
	return err
}
