// Package generate writes Ninja and compilation-database integration files.
package generate

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"maps"
	"os"
	"path/filepath"
	"slices"

	"github.com/Duncaen/go-ninja"

	"github.com/loov/clue/internal/config"
	"github.com/loov/clue/internal/deps"
	"github.com/loov/clue/internal/plan"
	"github.com/loov/clue/internal/toolchain"
)

// NinjaOptions holds options for generating build.ninja
type NinjaOptions struct {
	Config     *config.Config
	Variants   []string           // Variants to include (e.g., ["debug", "release"])
	BuildDir   string             // e.g., ".build"
	OutputPath string             // Output file path (default: build.ninja)
	Toolchain  string             // "clang" or "gcc"
	Platform   toolchain.Platform // Target platform
	Clue       string             // clue executable the build calls (default: this one)
	// Regenerate are the clue arguments that write OutputPath again; when
	// set, ninja reruns them once a file the configuration uses changes.
	Regenerate []string
}

// Ninja creates a build.ninja file for the project
func Ninja(ctx context.Context, opts NinjaOptions) error {
	if opts.OutputPath == "" {
		opts.OutputPath = "build.ninja"
	}
	var buf bytes.Buffer
	if err := WriteNinjaTo(ctx, &buf, opts); err != nil {
		return err
	}
	return writeIfChanged(opts.OutputPath, buf.Bytes())
}

// generateVariantBuilds generates build statements for a single variant
func generateVariantBuilds(ctx context.Context, file *ninja.File, opts NinjaOptions, variant string, variantConfig config.Variant, targetOrder []string, tc toolchain.Toolchain, emitSharedRules bool) ([]string, error) {
	external, err := resolveExternalDependencies(ctx, opts.Config, tc, opts.BuildDir, variant, opts.Platform)
	if err != nil {
		return nil, err
	}
	outputs, err := generateDependencyBuilds(ctx, file, opts, variant, variantConfig, tc, emitSharedRules, external)
	if err != nil {
		return nil, err
	}

	targetModules := make(map[string]map[string]string)
	for _, targetName := range targetOrder {
		target, exists := opts.Config.Targets[targetName]
		if !exists {
			continue
		}

		// Generate build statements for this target
		targetOutputs, err := generateTargetBuilds(file, opts, variant, variantConfig, target, tc, emitSharedRules, targetModules, external)
		if err != nil {
			return nil, err
		}
		// The variant's phony target builds what clue build builds; the
		// edges of optional targets remain for those that need them.
		if !target.Optional {
			outputs = append(outputs, targetOutputs...)
		}
	}

	return outputs, nil
}

// writeIfChanged writes content to file only if it differs from existing content
func writeIfChanged(path string, content []byte) error {
	existing, err := os.ReadFile(path)
	if err == nil && bytes.Equal(existing, content) {
		return nil // No change needed
	}

	return os.WriteFile(path, content, 0o644)
}

// WriteNinjaTo writes Ninja file content to a writer (for testing)
func WriteNinjaTo(ctx context.Context, w io.Writer, opts NinjaOptions) error {
	// Set defaults
	if opts.BuildDir == "" {
		opts.BuildDir = ".build"
	}
	if opts.Toolchain == "" {
		opts.Toolchain = opts.Config.Toolchain.Compiler
	}
	if opts.Platform.OS == "" {
		opts.Platform = toolchain.HostPlatform()
	}
	if len(opts.Variants) == 0 {
		for name := range opts.Config.Variants {
			opts.Variants = append(opts.Variants, name)
		}
		if len(opts.Variants) == 0 {
			opts.Variants = []string{"debug"}
		}
		slices.Sort(opts.Variants)
	}

	if err := config.ExpandTargetGlobs(opts.Config); err != nil {
		return fmt.Errorf("%w (run 'clue deps fetch' before generating)", err)
	}

	// Discover toolchain
	toolchain, err := configuredToolchain(opts.Config.Toolchain, opts.Toolchain, opts.Platform)
	if err != nil {
		return err
	}

	file := ninja.File{}

	// Header comment
	file = append(file, ninja.Comment{Lines: []string{"Generated by clue. Regenerate with: clue generate ninja"}})

	// Variables
	file = append(file, ninja.Comment{Lines: []string{"Build configuration"}})
	file = append(file, ninja.Var{Key: "builddir", Val: ninja.Escape(NinjaPath(opts.BuildDir))})
	file = append(file, ninja.Var{Key: "cc", Val: ninjaToolCommand(toolchain, toolchain.CC())})
	file = append(file, ninja.Var{Key: "cxx", Val: ninjaToolCommand(toolchain, toolchain.CXX())})
	file = append(file, ninja.Var{Key: "ar", Val: ninjaToolCommand(toolchain, toolchain.AR())})
	if opts.Clue == "" {
		opts.Clue = "clue"
		if executable, err := os.Executable(); err == nil {
			opts.Clue = executable
		}
	}
	file = append(file, ninja.Var{Key: "clue", Val: ninjaShellCommand([]string{opts.Clue})})
	if toolchain.Name() == "msvc" {
		linker := plan.Link(toolchain, opts.Platform, plan.LinkOptions{}).Tool
		file = append(file, ninja.Var{Key: "link", Val: ninjaToolCommand(toolchain, linker)})
	}

	// Rules
	file = append(file, ninja.Comment{Lines: []string{"Compilation rules"}})
	addNinjaRules(&file, toolchain.Name() == "msvc")
	file = append(file, ninja.Pool{Name: "fetch", Depth: 1})
	file = append(file, ninja.Build{Rule: "phony", Out: []string{"force_external"}})
	if len(opts.Regenerate) > 0 {
		addRegeneration(&file, opts)
	}

	targetOrder, err := config.ComputeBuildOrder(opts.Config)
	if err != nil {
		return err
	}
	variantOutputs := make(map[string][]string)

	for variantIndex, variant := range opts.Variants {
		variantConfig, exists := opts.Config.Variants[variant]
		if !exists && len(opts.Config.Variants) > 0 {
			return fmt.Errorf("variant %q not found", variant)
		}
		file = append(file, ninja.Comment{Lines: []string{"Variant: " + variant}})
		outputs, err := generateVariantBuilds(ctx, &file, opts, variant, variantConfig, targetOrder, toolchain, variantIndex == 0)
		if err != nil {
			return err
		}
		variantOutputs[variant] = outputs
	}

	// Phony targets
	file = append(file, ninja.Comment{Lines: []string{"Phony targets"}})
	for _, variant := range opts.Variants {
		if outputs, ok := variantOutputs[variant]; ok && len(outputs) > 0 {
			file = append(file, ninja.Build{
				Rule: "phony",
				In:   outputs,
				Out:  []string{variant},
			})
		}
	}

	if len(opts.Variants) > 0 {
		defaultVariant := opts.Variants[0]
		if slices.Contains(opts.Variants, opts.Config.DefaultVariant) {
			defaultVariant = opts.Config.DefaultVariant
		}
		file = append(file, defaultTarget{targets: []string{defaultVariant}})
	}

	escapeBuildPaths(file)
	_, err = file.WriteTo(w)
	return err
}

// addRegeneration makes the Ninja file depend on the files the configuration
// was loaded from: its CUE files, dependency description files and patches.
// Editing a patch, for one, changes the directory of the patched sources.
func addRegeneration(file *ninja.File, opts NinjaOptions) {
	relative := func(path string) string {
		if absolute, err := filepath.Abs(path); err == nil {
			path = absolute
		}
		if rel, err := filepath.Rel(opts.Config.Dir, path); err == nil && filepath.IsLocal(rel) {
			path = rel
		}
		return NinjaPath(path)
	}
	inputs := make([]string, 0, len(opts.Config.Files))
	for _, path := range opts.Config.Files {
		inputs = append(inputs, relative(path))
	}
	for _, name := range slices.Sorted(maps.Keys(opts.Config.Dependencies)) {
		dependency := opts.Config.Dependencies[name]
		if path := dependency.ConfigFile(); path != "" {
			if !filepath.IsAbs(path) {
				path = filepath.Join(opts.Config.Dir, path)
			}
			inputs = append(inputs, relative(path))
		}
		for _, patch := range deps.Patches(dependency) {
			inputs = append(inputs, relative(patch.Path))
		}
	}
	slices.Sort(inputs)
	inputs = slices.Compact(inputs)
	// A removed configuration file must still allow regeneration of the old
	// graph. Existing files retain their timestamps through these phony edges.
	for _, input := range inputs {
		*file = append(*file, ninja.Build{Rule: "phony", Out: []string{input}})
	}
	*file = append(*file, ninja.Rule{
		Name: "regen", Command: "$clue " + ninjaShellCommand(opts.Regenerate), Description: "REGENERATE $out",
		// Restat: clue leaves an unchanged Ninja file as it is.
		Generator: true, Restat: true,
	}, ninja.Build{Rule: "regen", Out: []string{relative(opts.OutputPath)}, In: inputs})
}

// escapeBuildPaths applies ninja's path escaping ("$", ":", space, newline) to
// every path of every build statement, so paths with spaces or drive letters work.
func escapeBuildPaths(file ninja.File) {
	escape := func(paths []string) []string {
		escaped := make([]string, len(paths))
		for index, path := range paths {
			escaped[index] = ninja.Escape(path)
		}
		return escaped
	}
	for index, node := range file {
		if build, ok := node.(ninja.Build); ok {
			build.Out, build.OutImplicit = escape(build.Out), escape(build.OutImplicit)
			build.In, build.InImplicit, build.InOrderOnly = escape(build.In), escape(build.InImplicit), escape(build.InOrderOnly)
			file[index] = build
		}
	}
}
