package generate

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/Duncaen/go-ninja"

	"github.com/loov/clue/internal/build"
	"github.com/loov/clue/internal/config"
	"github.com/loov/clue/internal/deps"
	"github.com/loov/clue/internal/toolchain"
	"github.com/loov/clue/internal/toolchain/msvc"
)

// createMinimalConfig creates a minimal config for testing
func createMinimalConfig(targetName, targetType string, sources []string) *config.Config {
	return &config.Config{
		Name:     "test-project",
		BuildDir: ".build",
		Toolchain: config.Toolchain{
			Compiler: "clang",
			Std:      "c++20",
		},
		Targets: map[string]config.Target{
			targetName: {
				Name:    targetName,
				Type:    targetType,
				Sources: sources,
			},
		},
		Variants: map[string]config.Variant{
			"debug": {
				Name:      "debug",
				DebugInfo: true,
			},
		},
	}
}

func TestNinja_BasicStructure(t *testing.T) {
	cfg := createMinimalConfig("myapp", "executable", []string{"main.cpp"})

	var buf bytes.Buffer
	err := WriteNinjaTo(&buf, NinjaOptions{
		Config:    cfg,
		Variants:  []string{"debug"},
		BuildDir:  ".build",
		Toolchain: "clang",
		Platform:  toolchain.Platform{OS: "linux", Arch: "amd64"},
	})
	if err != nil {
		t.Fatalf("WriteNinjaTo failed: %v", err)
	}

	content := buf.String()

	// Verify header comment
	if !strings.Contains(content, "# Generated by clue") {
		t.Error("Missing generated comment")
	}

	// Verify cc rule
	if !strings.Contains(content, "rule cc") {
		t.Error("Missing cc rule")
	}

	// Verify cxx rule
	if !strings.Contains(content, "rule cxx") {
		t.Error("Missing cxx rule")
	}

	// Verify link rule
	if !strings.Contains(content, "rule link") {
		t.Error("Missing link rule")
	}

	// Verify build statement for source
	if !strings.Contains(content, "build .build/debug/myapp/obj/main.cpp.o") {
		t.Errorf("Missing build statement for main.cpp.o, got:\n%s", content)
	}

	// Verify link statement
	if !strings.Contains(content, "build .build/debug/bin/myapp") {
		t.Errorf("Missing link statement for myapp, got:\n%s", content)
	}

	// Verify phony target
	if !strings.Contains(content, "build debug: phony") {
		t.Errorf("Missing phony target for debug, got:\n%s", content)
	}

	// Verify default target
	if !strings.Contains(content, "default debug") {
		t.Errorf("Missing default target, got:\n%s", content)
	}
}

func TestNinja_CustomTargetGeneratesBeforeConsumer(t *testing.T) {
	cfg := createMinimalConfig("app", "executable", []string{"generated.cpp"})
	cfg.Targets["app"] = config.Target{
		Name: "app", Type: "executable", Sources: []string{"generated.cpp"}, Depends: []string{"generate"},
	}
	cfg.Targets["generate"] = config.Target{
		Name: "generate", Type: "custom", Command: []string{"generator"},
		Inputs: []string{"schema.idl"}, Outputs: []string{"generated.cpp"},
	}
	var output bytes.Buffer
	if err := WriteNinjaTo(&output, NinjaOptions{
		Config: cfg, Variants: []string{"debug"}, BuildDir: ".build", Toolchain: "clang",
		Platform: toolchain.Platform{OS: "linux", Arch: "amd64"},
	}); err != nil {
		t.Fatal(err)
	}
	content := output.String()
	for _, want := range []string{
		"build generated.cpp: custom schema.idl",
		"build .build/debug/app/obj/generated.cpp.o: cxx generated.cpp || generated.cpp",
		"command = $clue -variant $variant -target $platform build $target",
	} {
		if !strings.Contains(content, want) {
			t.Errorf("Ninja output missing %q:\n%s", want, content)
		}
	}
}

func TestTargetModules_WiresProducedBMIsToConsumers(t *testing.T) {
	modules := targetModules{
		bySource: map[string]build.ModuleDependency{
			"hello.cppm": {Source: "hello.cppm", Provides: "hello"},
			"main.cpp":   {Source: "main.cpp", Requires: []string{"hello"}},
		},
		outputs: map[string]string{"hello": ".build/debug/app/modules/hello.pcm"},
	}
	if got := strings.Join(modules.flags("main.cpp"), " "); got != "-fmodule-file=hello=.build/debug/app/modules/hello.pcm" {
		t.Fatalf("consumer flags = %q", got)
	}
	if got := modules.inputs("main.cpp"); len(got) != 1 || got[0] != ".build/debug/app/modules/hello.pcm" {
		t.Fatalf("consumer inputs = %v", got)
	}
}

func TestNinja_DefaultVariantWithoutConfiguration(t *testing.T) {
	cfg := createMinimalConfig("myapp", "executable", []string{"main.cpp"})
	cfg.Variants = nil

	var buf bytes.Buffer
	if err := WriteNinjaTo(&buf, NinjaOptions{
		Config: cfg, BuildDir: ".build", Toolchain: "clang",
		Platform: toolchain.Platform{OS: "linux", Arch: "amd64"},
	}); err != nil {
		t.Fatal(err)
	}
	content := buf.String()
	if !strings.Contains(content, "build .build/debug/bin/myapp") ||
		!strings.Contains(content, "build debug: phony") ||
		!strings.Contains(content, "default debug") {
		t.Errorf("default variant has incomplete Ninja output:\n%s", content)
	}
}

func TestNinja_Depfile(t *testing.T) {
	cfg := createMinimalConfig("myapp", "executable", []string{"main.c"})

	var buf bytes.Buffer
	err := WriteNinjaTo(&buf, NinjaOptions{
		Config:    cfg,
		Variants:  []string{"debug"},
		BuildDir:  ".build",
		Toolchain: "clang",
		Platform:  toolchain.Platform{OS: "linux", Arch: "amd64"},
	})
	if err != nil {
		t.Fatalf("WriteNinjaTo failed: %v", err)
	}

	content := buf.String()

	// Verify depfile in cc rule
	if !strings.Contains(content, "depfile = $out.d") {
		t.Error("Missing depfile = $out.d in rules")
	}

	// Verify deps = gcc
	if !strings.Contains(content, "deps = gcc") {
		t.Error("Missing deps = gcc in rules")
	}

	// Verify -MD -MF in command
	if !strings.Contains(content, "-MD -MF $out.d") {
		t.Error("Missing -MD -MF $out.d in compile command")
	}
}

func TestNinja_MultiVariant(t *testing.T) {
	cfg := &config.Config{
		Name:     "test-project",
		BuildDir: ".build",
		Toolchain: config.Toolchain{
			Compiler: "clang",
			Std:      "c++20",
		},
		Targets: map[string]config.Target{
			"myapp": {
				Name:    "myapp",
				Type:    "executable",
				Sources: []string{"main.cpp"},
			},
		},
		Variants: map[string]config.Variant{
			"debug": {
				Name:         "debug",
				DebugInfo:    true,
				Optimization: "none",
			},
			"release": {
				Name:         "release",
				DebugInfo:    false,
				Optimization: "fast",
			},
		},
	}

	var buf bytes.Buffer
	err := WriteNinjaTo(&buf, NinjaOptions{
		Config:    cfg,
		Variants:  []string{"debug", "release"},
		BuildDir:  ".build",
		Toolchain: "clang",
		Platform:  toolchain.Platform{OS: "linux", Arch: "amd64"},
	})
	if err != nil {
		t.Fatalf("WriteNinjaTo failed: %v", err)
	}

	content := buf.String()

	// Verify both phony targets exist
	if !strings.Contains(content, "build debug: phony") {
		t.Error("Missing phony target for debug")
	}
	if !strings.Contains(content, "build release: phony") {
		t.Error("Missing phony target for release")
	}

	// Verify build statements for both variants
	if !strings.Contains(content, ".build/debug/bin/myapp") {
		t.Error("Missing debug variant output")
	}
	if !strings.Contains(content, ".build/release/bin/myapp") {
		t.Error("Missing release variant output")
	}

	// Verify default is first variant (debug)
	if !strings.Contains(content, "default debug") {
		t.Error("Default should be first variant (debug)")
	}
}

func TestNinja_StaticLibrary(t *testing.T) {
	cfg := createMinimalConfig("mylib", "static_library", []string{"lib.cpp"})

	var buf bytes.Buffer
	err := WriteNinjaTo(&buf, NinjaOptions{
		Config:    cfg,
		Variants:  []string{"debug"},
		BuildDir:  ".build",
		Toolchain: "clang",
		Platform:  toolchain.Platform{OS: "linux", Arch: "amd64"},
	})
	if err != nil {
		t.Fatalf("WriteNinjaTo failed: %v", err)
	}

	content := buf.String()

	// Verify ar rule exists
	if !strings.Contains(content, "rule ar") {
		t.Error("Missing ar rule")
	}

	// Verify ar command
	if !strings.Contains(content, "$ar crs $out $in") {
		t.Error("Missing ar crs command")
	}

	// Verify library output uses ar rule
	if !strings.Contains(content, "build .build/debug/lib/libmylib.a: ar") {
		t.Errorf("Missing ar build statement for libmylib.a, got:\n%s", content)
	}
}

func TestNinja_LinksTargetDependenciesInOrder(t *testing.T) {
	cfg := createMinimalConfig("app", "executable", []string{"main.cpp"})
	cfg.Targets["app"] = config.Target{
		Name: "app", Type: "executable", Sources: []string{"main.cpp"}, Depends: []string{"first"},
	}
	cfg.Targets["first"] = config.Target{
		Name: "first", Type: "static_library", Sources: []string{"first.cpp"}, Depends: []string{"second"},
	}
	cfg.Targets["second"] = config.Target{
		Name: "second", Type: "static_library", Sources: []string{"second.cpp"}, SysLibs: []string{"pthread"},
	}

	var buf bytes.Buffer
	if err := WriteNinjaTo(&buf, NinjaOptions{
		Config: cfg, Variants: []string{"debug"}, BuildDir: ".build", Toolchain: "clang",
		Platform: toolchain.Platform{OS: "linux", Arch: "amd64"},
	}); err != nil {
		t.Fatal(err)
	}

	content := buf.String()
	want := "build .build/debug/bin/app: link .build/debug/app/obj/main.cpp.o .build/debug/lib/libfirst.a .build/debug/lib/libsecond.a"
	if !strings.Contains(content, want) {
		t.Errorf("target libraries are not ordered link inputs:\n%s", content)
	}
	if !strings.Contains(content, "ldflags = -lpthread") {
		t.Errorf("transitive system libraries are missing:\n%s", content)
	}
}

func TestNinja_BuildsExternalDependencies(t *testing.T) {
	root := t.TempDir()
	depRoot := filepath.Join(root, "vendor", "math")
	if err := os.MkdirAll(filepath.Join(depRoot, "include"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(depRoot, "math.cpp"), nil, 0o644); err != nil {
		t.Fatal(err)
	}

	cfg := createMinimalConfig("app", "executable", []string{"main.cpp"})
	cfg.Targets["app"] = config.Target{
		Name: "app", Type: "executable", Sources: []string{"main.cpp"}, Depends: []string{"math"},
	}
	cfg.Dependencies = map[string]deps.Dependency{
		"math": deps.NewVendoredDependency("math", depRoot, &deps.InlineConfig{
			Sources: []string{"*.cpp"}, Includes: []string{"include"}, Defines: []string{"MATH_BUILD"},
		}),
	}
	cfg.Variants["release"] = config.Variant{Name: "release", Optimization: "fast"}

	var buf bytes.Buffer
	if err := WriteNinjaTo(&buf, NinjaOptions{
		Config: cfg, Variants: []string{"debug", "release"}, BuildDir: ".build", Toolchain: "clang",
		Platform: toolchain.Platform{OS: "linux", Arch: "amd64"},
	}); err != nil {
		t.Fatal(err)
	}

	content := buf.String()
	checks := []string{
		"rule fetch_dep",
		"command = $clue deps fetch $dep",
		"build .build/debug/deps/math/obj/math.cpp.o: cxx " + ninjaPathLocal(filepath.Join(depRoot, "math.cpp")),
		"-I" + ninjaPathLocal(filepath.Join(depRoot, "include")),
		"-DMATH_BUILD",
		"build .build/debug/deps/math/lib/libmath.a: ar .build/debug/deps/math/obj/math.cpp.o",
		"build .build/debug/bin/app: link .build/debug/app/obj/main.cpp.o .build/debug/deps/math/lib/libmath.a",
	}
	for _, check := range checks {
		if !strings.Contains(content, check) {
			t.Errorf("missing %q in Ninja output:\n%s", check, content)
		}
	}
	if count := strings.Count(content, ": fetch_dep "); count != 1 {
		t.Errorf("expected one fetch edge shared by variants, got %d:\n%s", count, content)
	}
}

func TestNinja_HeaderOnlyDependencyAddsIncludesWithoutLibrary(t *testing.T) {
	root := filepath.Join(t.TempDir(), "headers")
	cfg := createMinimalConfig("app", "executable", []string{"main.cpp"})
	cfg.Targets["app"] = config.Target{
		Name: "app", Type: "executable", Sources: []string{"main.cpp"}, Depends: []string{"headers"},
	}
	cfg.Dependencies = map[string]deps.Dependency{
		"headers": deps.NewVendoredDependency("headers", root, &deps.InlineConfig{
			Type: "header_only", Includes: []string{"include"},
		}),
	}

	var output bytes.Buffer
	if err := WriteNinjaTo(&output, NinjaOptions{
		Config: cfg, Variants: []string{"debug"}, BuildDir: ".build", Toolchain: "clang",
		Platform: toolchain.Platform{OS: "linux", Arch: "amd64"},
	}); err != nil {
		t.Fatal(err)
	}
	content := output.String()
	if !strings.Contains(content, "-I"+ninjaPathLocal(filepath.Join(root, "include"))) {
		t.Fatalf("header include is missing:\n%s", content)
	}
	if strings.Contains(content, "libheaders") {
		t.Fatalf("header-only dependency produced a library:\n%s", content)
	}
}

func TestNinja_BuildsDependencyWithClueConfig(t *testing.T) {
	depRoot := t.TempDir()
	if err := os.WriteFile(filepath.Join(depRoot, "lib.c"), nil, 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(depRoot, "clue.cue"), []byte(`
targets: lib: {
	type: "shared_library"
	sources: ["lib.c"]
}
`), 0o644); err != nil {
		t.Fatal(err)
	}
	cfg := createMinimalConfig("app", "executable", []string{"main.c"})
	cfg.Targets["app"] = config.Target{
		Name: "app", Type: "executable", Sources: []string{"main.c"}, Depends: []string{"lib"},
	}
	cfg.Dependencies = map[string]deps.Dependency{
		"lib": deps.NewVendoredDependency("lib", depRoot, nil),
	}

	var buf bytes.Buffer
	if err := WriteNinjaTo(&buf, NinjaOptions{
		Config: cfg, Variants: []string{"debug"}, BuildDir: ".build", Toolchain: "clang",
		Platform: toolchain.Platform{OS: "linux", Arch: "amd64"},
	}); err != nil {
		t.Fatal(err)
	}
	if want := ninjaPathLocal(filepath.Join(depRoot, "lib.c")); !strings.Contains(buf.String(), want) {
		t.Errorf("dependency clue.cue source is missing from Ninja output:\n%s", buf.String())
	}
	checks := []string{
		"build .build/debug/deps/lib/lib/liblib.so: link_shared",
		"build .build/debug/bin/app: link .build/debug/app/obj/main.c.o .build/debug/deps/lib/lib/liblib.so",
		"-Wl,-rpath,$$ORIGIN/../deps/lib/lib",
	}
	for _, check := range checks {
		if !strings.Contains(buf.String(), check) {
			t.Errorf("missing %q in Ninja output:\n%s", check, buf.String())
		}
	}
}

func TestNinja_SharedLibrary(t *testing.T) {
	cfg := createMinimalConfig("mylib", "shared_library", []string{"lib.cpp"})

	var buf bytes.Buffer
	err := WriteNinjaTo(&buf, NinjaOptions{
		Config:    cfg,
		Variants:  []string{"debug"},
		BuildDir:  ".build",
		Toolchain: "clang",
		Platform:  toolchain.Platform{OS: "linux", Arch: "amd64"},
	})
	if err != nil {
		t.Fatalf("WriteNinjaTo failed: %v", err)
	}

	content := buf.String()

	// Verify link_shared rule exists
	if !strings.Contains(content, "rule link_shared") {
		t.Error("Missing link_shared rule")
	}

	// Verify -shared in command
	if !strings.Contains(content, "-shared $in -o $out") {
		t.Error("Missing -shared flag in link_shared command")
	}

	// Verify library output uses link_shared rule
	if !strings.Contains(content, "build .build/debug/lib/libmylib.so: link_shared") {
		t.Errorf("Missing link_shared build statement for libmylib.so, got:\n%s", content)
	}

	// Verify -fPIC in cxxflags for shared library objects
	if !strings.Contains(content, "-fPIC") {
		t.Errorf("Missing -fPIC for shared library, got:\n%s", content)
	}

	// Verify soname on Linux
	if !strings.Contains(content, "-Wl,-soname,libmylib.so") {
		t.Errorf("Missing -Wl,-soname on Linux, got:\n%s", content)
	}
}

func TestNinja_SharedLibrary_Darwin(t *testing.T) {
	cfg := createMinimalConfig("mylib", "shared_library", []string{"lib.cpp"})

	var buf bytes.Buffer
	err := WriteNinjaTo(&buf, NinjaOptions{
		Config:    cfg,
		Variants:  []string{"debug"},
		BuildDir:  ".build",
		Toolchain: "clang",
		Platform:  toolchain.Platform{OS: "darwin", Arch: "arm64"},
	})
	if err != nil {
		t.Fatalf("WriteNinjaTo failed: %v", err)
	}

	content := buf.String()

	// Verify .dylib extension on Darwin
	if !strings.Contains(content, "libmylib.dylib") {
		t.Errorf("Missing .dylib extension on Darwin, got:\n%s", content)
	}

	// Verify install_name on Darwin
	if !strings.Contains(content, "-install_name @rpath/libmylib.dylib") {
		t.Errorf("Missing -install_name on Darwin, got:\n%s", content)
	}
}

func TestOutputNameForTarget_Windows(t *testing.T) {
	platform := toolchain.Platform{OS: "windows", Arch: "amd64"}
	tests := map[string]string{
		"executable":     "app.exe",
		"static_library": "app.lib",
		"shared_library": "app.dll",
	}
	for targetType, want := range tests {
		if got := outputNameForTarget("app", targetType, platform); got != want {
			t.Errorf("outputNameForTarget(%q) = %q, want %q", targetType, got, want)
		}
	}
}

func TestNinja_MSVCUsesNativeSyntax(t *testing.T) {
	platform := toolchain.Platform{OS: "windows", Arch: "amd64"}
	tc, err := msvc.New(&msvc.Installation{Environment: map[string]string{
		"INCLUDE": `C:\Program Files\VS\include;C:\SDK\include`,
		"LIB":     `C:\Program Files\VS\lib`,
	}}, platform)
	if err != nil {
		t.Fatal(err)
	}
	cfg := createMinimalConfig("mylib", "shared_library", []string{"lib.cpp"})
	cfg.Targets["mylib"] = config.Target{
		Name: "mylib", Type: "shared_library", Sources: []string{"lib.cpp"},
		Includes: []string{"include"}, Defines: []string{"BUILDING_LIB"},
	}
	opts := NinjaOptions{Config: cfg, BuildDir: ".build", Toolchain: "msvc", Platform: platform}

	file := ninja.File{}
	addNinjaRules(&file, true)
	if _, err := generateTargetBuilds(&file, opts, "debug", cfg.Variants["debug"], cfg.Targets["mylib"], tc, true); err != nil {
		t.Fatal(err)
	}
	var buf bytes.Buffer
	if _, err := file.WriteTo(&buf); err != nil {
		t.Fatal(err)
	}
	content := buf.String()
	checks := []string{
		`command = "$cc" $cflags /c $in /Fo"$out"`,
		"deps = msvc",
		`/std:c++20 /Iinclude /I"C:\Program Files\VS\include" /IC:\SDK\include /DBUILDING_LIB`,
		`command = "$link" /DLL $in /OUT:"$out" /IMPLIB:"$implib" $ldflags`,
		`/LIBPATH:"C:\Program Files\VS\lib"`,
		"build .build/debug/lib/mylib.dll | .build/debug/lib/mylib.lib: link_shared",
		"implib = .build/debug/lib/mylib.lib",
	}
	for _, check := range checks {
		if !strings.Contains(content, check) {
			t.Errorf("missing %q in MSVC Ninja output:\n%s", check, content)
		}
	}
	if strings.Contains(content, "-fPIC") || strings.Contains(content, "-MD") {
		t.Errorf("GCC flags leaked into MSVC Ninja output:\n%s", content)
	}
}

func TestNinja_IncludesAndDefines(t *testing.T) {
	cfg := &config.Config{
		Name:     "test-project",
		BuildDir: ".build",
		Toolchain: config.Toolchain{
			Compiler: "clang",
			Std:      "c++20",
		},
		Targets: map[string]config.Target{
			"myapp": {
				Name:     "myapp",
				Type:     "executable",
				Sources:  []string{"main.cpp"},
				Includes: []string{"include", "vendor/lib"},
				Defines:  []string{"DEBUG", "VERSION=1"},
			},
		},
		Variants: map[string]config.Variant{
			"debug": {Name: "debug", DebugInfo: true},
		},
	}

	var buf bytes.Buffer
	err := WriteNinjaTo(&buf, NinjaOptions{
		Config:    cfg,
		Variants:  []string{"debug"},
		BuildDir:  ".build",
		Toolchain: "clang",
		Platform:  toolchain.Platform{OS: "linux", Arch: "amd64"},
	})
	if err != nil {
		t.Fatalf("WriteNinjaTo failed: %v", err)
	}

	content := buf.String()

	// Verify include paths
	if !strings.Contains(content, "-Iinclude") {
		t.Error("Missing -Iinclude flag")
	}
	if !strings.Contains(content, "-Ivendor/lib") {
		t.Error("Missing -Ivendor/lib flag")
	}

	// Verify defines
	if !strings.Contains(content, "-DDEBUG") {
		t.Error("Missing -DDEBUG flag")
	}
	if !strings.Contains(content, "-DVERSION=1") {
		t.Error("Missing -DVERSION=1 flag")
	}
}

func TestNinja_ForwardSlashes(t *testing.T) {
	cfg := &config.Config{
		Name:     "test-project",
		BuildDir: ".build",
		Toolchain: config.Toolchain{
			Compiler: "clang",
			Std:      "c++20",
		},
		Targets: map[string]config.Target{
			"myapp": {
				Name:     "myapp",
				Type:     "executable",
				Sources:  []string{"src/main.cpp", "src/util/helper.cpp"},
				Includes: []string{"include/myapp"},
			},
		},
		Variants: map[string]config.Variant{
			"debug": {Name: "debug", DebugInfo: true},
		},
	}

	var buf bytes.Buffer
	err := WriteNinjaTo(&buf, NinjaOptions{
		Config:    cfg,
		Variants:  []string{"debug"},
		BuildDir:  ".build",
		Toolchain: "clang",
		Platform:  toolchain.Platform{OS: "linux", Arch: "amd64"},
	})
	if err != nil {
		t.Fatalf("WriteNinjaTo failed: %v", err)
	}

	content := buf.String()

	// Verify paths use forward slashes (not backslashes)
	if strings.Contains(content, "\\") {
		t.Errorf("Found backslash in generated ninja file, should use forward slashes:\n%s", content)
	}

	// Verify source paths with subdirectories
	if !strings.Contains(content, "src/main.cpp") {
		t.Error("Missing src/main.cpp with forward slashes")
	}
	if !strings.Contains(content, "src/util/helper.cpp") {
		t.Error("Missing src/util/helper.cpp with forward slashes")
	}

	// Verify include path with subdirectory
	if !strings.Contains(content, "-Iinclude/myapp") {
		t.Error("Missing -Iinclude/myapp with forward slashes")
	}
}

func TestNinja_WriteFile(t *testing.T) {
	// Create temp directory
	tmpDir := t.TempDir()

	cfg := createMinimalConfig("myapp", "executable", []string{"main.cpp"})

	outputPath := filepath.Join(tmpDir, "build.ninja")
	err := Ninja(NinjaOptions{
		Config:     cfg,
		Variants:   []string{"debug"},
		BuildDir:   ".build",
		OutputPath: outputPath,
		Toolchain:  "clang",
		Platform:   toolchain.Platform{OS: "linux", Arch: "amd64"},
	})
	if err != nil {
		t.Fatalf("Ninja failed: %v", err)
	}

	// Verify file exists
	if _, err := os.Stat(outputPath); os.IsNotExist(err) {
		t.Fatal("build.ninja was not created")
	}

	// Read and verify content
	content, err := os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("Failed to read build.ninja: %v", err)
	}

	if !strings.Contains(string(content), "rule cc") {
		t.Error("Generated file missing cc rule")
	}
}

func TestNinja_WriteIfChanged(t *testing.T) {
	tmpDir := t.TempDir()
	outputPath := filepath.Join(tmpDir, "build.ninja")

	cfg := createMinimalConfig("myapp", "executable", []string{"main.cpp"})
	opts := NinjaOptions{
		Config:     cfg,
		Variants:   []string{"debug"},
		BuildDir:   ".build",
		OutputPath: outputPath,
		Toolchain:  "clang",
		Platform:   toolchain.Platform{OS: "linux", Arch: "amd64"},
	}

	// Generate first time
	err := Ninja(opts)
	if err != nil {
		t.Fatalf("First Ninja failed: %v", err)
	}

	// Get file info
	info1, err := os.Stat(outputPath)
	if err != nil {
		t.Fatalf("Failed to stat file: %v", err)
	}
	mtime1 := info1.ModTime()

	// Generate second time with same content - should not modify
	err = Ninja(opts)
	if err != nil {
		t.Fatalf("Second Ninja failed: %v", err)
	}

	info2, err := os.Stat(outputPath)
	if err != nil {
		t.Fatalf("Failed to stat file after second write: %v", err)
	}
	mtime2 := info2.ModTime()

	// Mtime should be the same (file wasn't rewritten)
	if !mtime1.Equal(mtime2) {
		t.Error("File was rewritten even though content was unchanged")
	}
}

func TestNinja_CCompiler(t *testing.T) {
	// Test that C files use cc rule, not cxx
	cfg := createMinimalConfig("myapp", "executable", []string{"main.c"})

	var buf bytes.Buffer
	err := WriteNinjaTo(&buf, NinjaOptions{
		Config:    cfg,
		Variants:  []string{"debug"},
		BuildDir:  ".build",
		Toolchain: "clang",
		Platform:  toolchain.Platform{OS: "linux", Arch: "amd64"},
	})
	if err != nil {
		t.Fatalf("WriteNinjaTo failed: %v", err)
	}

	content := buf.String()

	// Verify C file uses cc rule (has cflags, not cxxflags)
	if !strings.Contains(content, "build .build/debug/myapp/obj/main.c.o: cc main.c") {
		t.Errorf("C file should use cc rule, got:\n%s", content)
	}

	// Verify cflags is set for the C build
	if !strings.Contains(content, "cflags =") {
		t.Error("Missing cflags for C compilation")
	}
}

func TestNinja_MixedSources(t *testing.T) {
	// Test project with both C and C++ files
	cfg := &config.Config{
		Name:     "test-project",
		BuildDir: ".build",
		Toolchain: config.Toolchain{
			Compiler: "clang",
			Std:      "c++20",
		},
		Targets: map[string]config.Target{
			"myapp": {
				Name:    "myapp",
				Type:    "executable",
				Sources: []string{"main.cpp", "util.c"},
			},
		},
		Variants: map[string]config.Variant{
			"debug": {Name: "debug", DebugInfo: true},
		},
	}

	var buf bytes.Buffer
	err := WriteNinjaTo(&buf, NinjaOptions{
		Config:    cfg,
		Variants:  []string{"debug"},
		BuildDir:  ".build",
		Toolchain: "clang",
		Platform:  toolchain.Platform{OS: "linux", Arch: "amd64"},
	})
	if err != nil {
		t.Fatalf("WriteNinjaTo failed: %v", err)
	}

	content := buf.String()

	// C++ file should use cxx rule
	if !strings.Contains(content, "build .build/debug/myapp/obj/main.cpp.o: cxx main.cpp") {
		t.Errorf("C++ file should use cxx rule, got:\n%s", content)
	}

	// C file should use cc rule
	if !strings.Contains(content, "build .build/debug/myapp/obj/util.c.o: cc util.c") {
		t.Errorf("C file should use cc rule, got:\n%s", content)
	}
}
