// Package generate provides build file generation for various build systems.
package generate

import (
	"bytes"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/Duncaen/go-ninja"

	"github.com/loov/clue/internal/build"
	"github.com/loov/clue/internal/config"
)

// NinjaOptions holds options for generating build.ninja
type NinjaOptions struct {
	Config     *config.Config
	Variants   []string       // Variants to include (e.g., ["debug", "release"])
	BuildDir   string         // e.g., ".build"
	OutputPath string         // Output file path (default: build.ninja)
	Toolchain  string         // "clang" or "gcc"
	Platform   build.Platform // Target platform
}

// defaultTarget is a custom Node for the ninja default statement
type defaultTarget struct {
	targets []string
}

func (d defaultTarget) WriteTo(w io.Writer) (int64, error) {
	line := "default " + strings.Join(d.targets, " ") + "\n"
	written, err := io.WriteString(w, line)
	return int64(written), err
}

func (d defaultTarget) RequiredVersion() ninja.Version {
	return ninja.Version(0)
}

// Ninja creates a build.ninja file for the project
func Ninja(opts NinjaOptions) error {
	// Set defaults
	if opts.OutputPath == "" {
		opts.OutputPath = "build.ninja"
	}
	if opts.BuildDir == "" {
		opts.BuildDir = ".build"
	}
	if opts.Toolchain == "" {
		opts.Toolchain = opts.Config.Toolchain.Compiler
	}
	if len(opts.Variants) == 0 {
		// Use all variants from config
		for name := range opts.Config.Variants {
			opts.Variants = append(opts.Variants, name)
		}
		sort.Strings(opts.Variants) // Deterministic order
	}

	// Discover toolchain for compiler paths
	toolchain, err := build.DiscoverToolchain(opts.Toolchain, opts.Platform)
	if err != nil {
		return err
	}

	file := ninja.File{}

	// Add header comment
	file = append(file, ninja.Comment{Lines: []string{"Generated by clue. Regenerate with: clue generate ninja"}})

	// Variables section
	file = append(file, ninja.Comment{Lines: []string{"Build configuration"}})
	file = append(file, ninja.Var{Key: "builddir", Val: ".ninja_build"})
	file = append(file, ninja.Var{Key: "cc", Val: toolchain.CC})
	file = append(file, ninja.Var{Key: "cxx", Val: toolchain.CXX})
	file = append(file, ninja.Var{Key: "ar", Val: toolchain.AR})

	// Rules section
	file = append(file, ninja.Comment{Lines: []string{"Compilation rules"}})

	// C compilation rule
	file = append(file, ninja.Rule{
		Name:        "cc",
		Command:     "$cc -MD -MF $out.d $cflags -c $in -o $out",
		Depfile:     "$out.d",
		Deps:        ninja.DepsGCC,
		Description: "CC $out",
	})

	// C++ compilation rule
	file = append(file, ninja.Rule{
		Name:        "cxx",
		Command:     "$cxx -MD -MF $out.d $cxxflags -c $in -o $out",
		Depfile:     "$out.d",
		Deps:        ninja.DepsGCC,
		Description: "CXX $out",
	})

	// Link executable rule
	file = append(file, ninja.Rule{
		Name:        "link",
		Command:     "$cxx $in -o $out $ldflags",
		Description: "LINK $out",
	})

	// Link shared library rule
	file = append(file, ninja.Rule{
		Name:        "link_shared",
		Command:     "$cxx -shared $in -o $out $ldflags",
		Description: "LINK_SHARED $out",
	})

	// Archive rule (static library)
	file = append(file, ninja.Rule{
		Name:        "ar",
		Command:     "$ar crs $out $in",
		Description: "AR $out",
	})

	// Get deterministic target order
	targetOrder := getSortedTargetNames(opts.Config)

	// Generate build statements for each variant
	variantOutputs := make(map[string][]string)

	for _, variant := range opts.Variants {
		variantConfig, exists := opts.Config.Variants[variant]
		if !exists {
			continue
		}

		file = append(file, ninja.Comment{Lines: []string{"Variant: " + variant}})

		outputs := generateVariantBuilds(&file, opts, variant, variantConfig, targetOrder, toolchain)
		variantOutputs[variant] = outputs
	}

	// Phony targets for variants
	file = append(file, ninja.Comment{Lines: []string{"Phony targets"}})
	for _, variant := range opts.Variants {
		if outputs, ok := variantOutputs[variant]; ok && len(outputs) > 0 {
			file = append(file, ninja.Build{
				Rule: "phony",
				In:   outputs,
				Out:  []string{variant},
			})
		}
	}

	// Default target (first variant)
	if len(opts.Variants) > 0 {
		file = append(file, defaultTarget{targets: []string{opts.Variants[0]}})
	}

	// Write to file using WriteIfChanged pattern
	var buf bytes.Buffer
	if _, err := file.WriteTo(&buf); err != nil {
		return err
	}

	return writeIfChanged(opts.OutputPath, buf.Bytes())
}

// generateVariantBuilds generates build statements for a single variant
func generateVariantBuilds(file *ninja.File, opts NinjaOptions, variant string, variantConfig config.Variant, targetOrder []string, toolchain *build.Toolchain) []string {
	var outputs []string

	for _, targetName := range targetOrder {
		target, exists := opts.Config.Targets[targetName]
		if !exists {
			continue
		}

		// Generate build statements for this target
		targetOutputs := generateTargetBuilds(file, opts, variant, variantConfig, target, toolchain)
		outputs = append(outputs, targetOutputs...)
	}

	return outputs
}

// generateTargetBuilds generates build statements for a single target within a variant
func generateTargetBuilds(file *ninja.File, opts NinjaOptions, variant string, variantConfig config.Variant, target config.Target, _ *build.Toolchain) []string {
	// Build configuration for flags
	buildCfg := targetToBuildConfig(target, variantConfig)

	// Collect include paths
	includes := target.Includes

	// Build compiler flags
	cflags := buildCompilerFlagsForNinja(opts.Config, target, buildCfg, includes, false)
	cxxflags := buildCompilerFlagsForNinja(opts.Config, target, buildCfg, includes, true)

	// Add -fPIC for shared libraries
	if target.Type == "shared_library" {
		cflags = append(cflags, "-fPIC")
		cxxflags = append(cxxflags, "-fPIC")
	}

	var objects []string

	for _, source := range target.Sources {
		// Determine object path
		objPath := ninjaPathLocal(objectPath(opts.BuildDir, variant, target.Name, source))
		srcPath := ninjaPathLocal(source)

		objects = append(objects, objPath)

		// Determine rule based on source extension
		rule := "cc"
		flags := strings.Join(cflags, " ")
		flagKey := "cflags"
		if isCPlusPlusFile(source) {
			rule = "cxx"
			flags = strings.Join(cxxflags, " ")
			flagKey = "cxxflags"
		}

		*file = append(*file, ninja.Build{
			Rule: rule,
			In:   []string{srcPath},
			Out:  []string{objPath},
			Vars: ninja.Vars{
				{Key: flagKey, Val: flags},
			},
		})
	}

	// Link or archive
	outputPath := ninjaPathLocal(outputPathForTarget(opts.BuildDir, variant, target.Name, target.Type, opts.Platform))

	switch target.Type {
	case "executable":
		ldflags := buildLinkerFlagsForNinja(opts.Config, target, buildCfg, opts.BuildDir, variant, opts.Platform)
		*file = append(*file, ninja.Build{
			Rule: "link",
			In:   objects,
			Out:  []string{outputPath},
			Vars: ninja.Vars{
				{Key: "ldflags", Val: strings.Join(ldflags, " ")},
			},
		})

	case "static_library":
		*file = append(*file, ninja.Build{
			Rule: "ar",
			In:   objects,
			Out:  []string{outputPath},
		})

	case "shared_library":
		ldflags := buildSharedLibLinkerFlags(opts.Config, target, buildCfg, opts.Platform)
		*file = append(*file, ninja.Build{
			Rule: "link_shared",
			In:   objects,
			Out:  []string{outputPath},
			Vars: ninja.Vars{
				{Key: "ldflags", Val: strings.Join(ldflags, " ")},
			},
		})
	}

	return []string{outputPath}
}

// Note: targetToBuildConfig is defined in compdb.go and shared between both generators
// Note: objectPath is defined in compdb.go and shared between both generators

// buildCompilerFlagsForNinja builds compiler flags for Ninja output
func buildCompilerFlagsForNinja(cfg *config.Config, target config.Target, buildCfg build.Config, includes []string, _ bool) []string {
	var flags []string

	// Language standard
	if cfg.Toolchain.Std != "" {
		flags = append(flags, "-std="+cfg.Toolchain.Std)
	}

	// Include paths
	for _, inc := range includes {
		flags = append(flags, "-I"+ninjaPathLocal(inc))
	}

	// Defines
	for _, def := range target.Defines {
		flags = append(flags, "-D"+def)
	}

	// Semantic flags from build package
	semanticFlags := build.CompilerFlags(buildCfg)
	flags = append(flags, semanticFlags...)

	return flags
}

// buildLinkerFlagsForNinja builds linker flags for executables
func buildLinkerFlagsForNinja(cfg *config.Config, target config.Target, buildCfg build.Config, buildDir, variant string, _ build.Platform) []string {
	var flags []string

	// Library search paths for dependencies
	for _, dep := range target.Depends {
		if _, isTarget := cfg.Targets[dep]; isTarget {
			// Target dependency - add library path
			libPath := ninjaPathLocal(filepath.Join(buildDir, variant, "lib"))
			flags = append(flags, "-L"+libPath)
			flags = append(flags, "-l"+dep)
		}
	}

	// System libraries
	for _, sysLib := range target.SysLibs {
		flags = append(flags, "-l"+sysLib)
	}

	// Semantic linker flags
	semanticFlags := build.LinkerFlags(buildCfg, []string{})
	flags = append(flags, semanticFlags...)

	return flags
}

// buildSharedLibLinkerFlags builds linker flags for shared libraries
func buildSharedLibLinkerFlags(_ *config.Config, target config.Target, buildCfg build.Config, platform build.Platform) []string {
	var flags []string

	// Platform-specific shared library flags
	switch platform.OS {
	case "darwin":
		libName := "lib" + target.Name + ".dylib"
		flags = append(flags, "-install_name", "@rpath/"+libName)
	case "linux":
		libName := "lib" + target.Name + ".so"
		flags = append(flags, "-Wl,-soname,"+libName)
	}

	// System libraries
	for _, sysLib := range target.SysLibs {
		flags = append(flags, "-l"+sysLib)
	}

	// Semantic linker flags
	semanticFlags := build.LinkerFlags(buildCfg, []string{})
	flags = append(flags, semanticFlags...)

	return flags
}

// Helper functions

// ninjaPathLocal converts a path to use forward slashes (Ninja convention)
// Note: this is a local version; NinjaPath in common.go is exported for external use
func ninjaPathLocal(path string) string {
	return filepath.ToSlash(filepath.Clean(path))
}

// outputPathForTarget returns the output path for a target
func outputPathForTarget(buildDir, variant, target, targetType string, platform build.Platform) string {
	switch targetType {
	case "executable":
		return filepath.Join(buildDir, variant, "bin", target)
	case "static_library":
		return filepath.Join(buildDir, variant, "lib", "lib"+target+".a")
	case "shared_library":
		ext := build.SharedLibraryExtension(platform)
		return filepath.Join(buildDir, variant, "lib", "lib"+target+ext)
	default:
		return filepath.Join(buildDir, variant, "bin", target)
	}
}

// Note: isCPlusPlusFile is defined in compdb.go and shared between both generators

// getSortedTargetNames returns target names in deterministic order
func getSortedTargetNames(cfg *config.Config) []string {
	names := make([]string, 0, len(cfg.Targets))
	for name := range cfg.Targets {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

// writeIfChanged writes content to file only if it differs from existing content
func writeIfChanged(path string, content []byte) error {
	existing, err := os.ReadFile(path)
	if err == nil && bytes.Equal(existing, content) {
		return nil // No change needed
	}

	return os.WriteFile(path, content, 0644)
}

// WriteNinjaTo writes Ninja file content to a writer (for testing)
func WriteNinjaTo(w io.Writer, opts NinjaOptions) error {
	// Set defaults
	if opts.BuildDir == "" {
		opts.BuildDir = ".build"
	}
	if opts.Toolchain == "" {
		opts.Toolchain = opts.Config.Toolchain.Compiler
	}
	if len(opts.Variants) == 0 {
		for name := range opts.Config.Variants {
			opts.Variants = append(opts.Variants, name)
		}
		sort.Strings(opts.Variants)
	}

	// Discover toolchain
	toolchain, err := build.DiscoverToolchain(opts.Toolchain, opts.Platform)
	if err != nil {
		return err
	}

	file := ninja.File{}

	// Header comment
	file = append(file, ninja.Comment{Lines: []string{"Generated by clue. Regenerate with: clue generate ninja"}})

	// Variables
	file = append(file, ninja.Comment{Lines: []string{"Build configuration"}})
	file = append(file, ninja.Var{Key: "builddir", Val: ".ninja_build"})
	file = append(file, ninja.Var{Key: "cc", Val: toolchain.CC})
	file = append(file, ninja.Var{Key: "cxx", Val: toolchain.CXX})
	file = append(file, ninja.Var{Key: "ar", Val: toolchain.AR})

	// Rules
	file = append(file, ninja.Comment{Lines: []string{"Compilation rules"}})
	file = append(file, ninja.Rule{
		Name:        "cc",
		Command:     "$cc -MD -MF $out.d $cflags -c $in -o $out",
		Depfile:     "$out.d",
		Deps:        ninja.DepsGCC,
		Description: "CC $out",
	})
	file = append(file, ninja.Rule{
		Name:        "cxx",
		Command:     "$cxx -MD -MF $out.d $cxxflags -c $in -o $out",
		Depfile:     "$out.d",
		Deps:        ninja.DepsGCC,
		Description: "CXX $out",
	})
	file = append(file, ninja.Rule{
		Name:        "link",
		Command:     "$cxx $in -o $out $ldflags",
		Description: "LINK $out",
	})
	file = append(file, ninja.Rule{
		Name:        "link_shared",
		Command:     "$cxx -shared $in -o $out $ldflags",
		Description: "LINK_SHARED $out",
	})
	file = append(file, ninja.Rule{
		Name:        "ar",
		Command:     "$ar crs $out $in",
		Description: "AR $out",
	})

	targetOrder := getSortedTargetNames(opts.Config)
	variantOutputs := make(map[string][]string)

	for _, variant := range opts.Variants {
		variantConfig, exists := opts.Config.Variants[variant]
		if !exists {
			continue
		}
		file = append(file, ninja.Comment{Lines: []string{"Variant: " + variant}})
		outputs := generateVariantBuilds(&file, opts, variant, variantConfig, targetOrder, toolchain)
		variantOutputs[variant] = outputs
	}

	// Phony targets
	file = append(file, ninja.Comment{Lines: []string{"Phony targets"}})
	for _, variant := range opts.Variants {
		if outputs, ok := variantOutputs[variant]; ok && len(outputs) > 0 {
			file = append(file, ninja.Build{
				Rule: "phony",
				In:   outputs,
				Out:  []string{variant},
			})
		}
	}

	if len(opts.Variants) > 0 {
		file = append(file, defaultTarget{targets: []string{opts.Variants[0]}})
	}

	_, err = file.WriteTo(w)
	return err
}
